#!/usr/bin/env bash
#
# Run locally exactly the checks the CI pipeline runs, so a push is not the
# first place a failure shows up.
#
#   scripts/check.sh            fmt, clippy, test, test --release
#   scripts/check.sh --fast     fmt, clippy, test  (skips the release test run)
#   scripts/check.sh --audit    additionally run cargo audit when installed
#
# Exits non-zero on the first failing check; prints a summary at the end.

set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
readonly REPO_ROOT
cd "$REPO_ROOT"

FAST=0
WITH_AUDIT=0

while [ $# -gt 0 ]; do
  case "$1" in
    --fast)  FAST=1; shift ;;
    --audit) WITH_AUDIT=1; shift ;;
    -h|--help)
      sed -n '3,10p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) printf 'unknown option: %s\n' "$1" >&2; exit 2 ;;
  esac
done

# Snapshot tests must never silently rewrite snapshots, exactly as in CI.
export INSTA_UPDATE=no
export CARGO_TERM_COLOR=always
export RUST_BACKTRACE=1

PASSED=()
step() {
  local name="$1"; shift
  printf '\033[1;34m==>\033[0m %s\n' "$name"
  "$@"
  PASSED+=("$name")
}

step "cargo fmt --all --check" \
  cargo fmt --all --check

step "cargo clippy --all-targets --all-features -- -D warnings" \
  cargo clippy --all-targets --all-features --locked -- -D warnings

step "cargo test --all-features --locked" \
  cargo test --all-features --locked

if [ "$FAST" -eq 0 ]; then
  step "cargo test --release --all-features --locked" \
    cargo test --release --all-features --locked
fi

# The man page and the completions are generated by the binary and shipped in
# every package; a generator that produces nothing must fail the build.
printf '\033[1;34m==>\033[0m generated man page and completions\n'
cargo build --release --locked --quiet
BIN="target/release/mdless"
"$BIN" --generate-man | grep -q '^\.TH mdless' \
  || { echo "error: --generate-man produced no .TH header" >&2; exit 1; }
for sh in bash zsh fish; do
  [ -n "$("$BIN" --generate-completions "$sh")" ] \
    || { echo "error: --generate-completions $sh produced nothing" >&2; exit 1; }
done
PASSED+=("generated man page and completions")

if [ "$WITH_AUDIT" -eq 1 ]; then
  if command -v cargo-audit >/dev/null 2>&1; then
    step "cargo audit" cargo audit --deny warnings
  else
    echo "note: cargo-audit is not installed; skipping (cargo install cargo-audit)" >&2
  fi
fi

if command -v shellcheck >/dev/null 2>&1; then
  step "shellcheck scripts/*.sh" shellcheck scripts/release.sh scripts/check.sh
else
  echo "note: shellcheck is not installed; skipping the script lint" >&2
fi

echo
printf '\033[1;32mall checks passed\033[0m\n'
for p in "${PASSED[@]}"; do
  printf '  ✓ %s\n' "$p"
done
