#!/usr/bin/env bash
#
# diple release builder.
#
# Produces every release artifact from a Git tag, so that a release is
# reproducible from that tag alone:
#
#   * release binaries for the supported targets
#   * the man page and the bash/zsh/fish completions, generated by the built
#     binary itself so they can never drift from the CLI
#   * .deb and .rpm packages
#   * one tarball per target (binary, man page, completions, README, LICENSE,
#     CHANGELOG)
#   * SHA256SUMS over every artifact
#   * release notes extracted from CHANGELOG.md
#
# Usage:
#   scripts/release.sh [vX.Y.Z] [options]
#
#   vX.Y.Z            tag to release; defaults to the tag pointing at HEAD
#   --output DIR      artifact directory (default: dist)
#   --allow-dirty     skip the clean-working-tree check (for local dry runs)
#   --skip-checks     skip fmt/clippy/test/test --release (for local dry runs)
#   --no-packages     do not build .deb/.rpm
#
# Targets that have no usable toolchain are skipped with a message and listed in
# the final summary; they never fail the release.

set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
readonly REPO_ROOT
cd "$REPO_ROOT"

# All targets we try to build. macOS targets need a cross toolchain and are
# normally skipped on Linux.
readonly ALL_TARGETS=(
  x86_64-unknown-linux-gnu
  x86_64-unknown-linux-musl
  aarch64-unknown-linux-musl
  x86_64-apple-darwin
  aarch64-apple-darwin
)

# The target whose binary is used to generate the man page and completions and
# to build the .deb/.rpm. It must be natively runnable on the build host.
HOST_TARGET="$(rustc -vV | sed -n 's/^host: //p')"
readonly HOST_TARGET

OUTPUT_DIR="dist"
ALLOW_DIRTY=0
SKIP_CHECKS=0
BUILD_PACKAGES=1
TAG=""

BUILT_TARGETS=()
SKIPPED_TARGETS=()
ARTIFACTS=()

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
info() { printf '    %s\n' "$*"; }
warn() { printf '\033[1;33mskip:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# Apparent file size, human readable. `du` reports allocated blocks, which on a
# compressing filesystem understates freshly written artifacts.
human_size() {
  local bytes units=(B KiB MiB GiB) i=0
  bytes="$(wc -c < "$1" | tr -d ' ')"
  while [ "$bytes" -ge 1024 ] && [ "$i" -lt 3 ]; do
    bytes=$(( bytes / 1024 ))
    i=$(( i + 1 ))
  done
  printf '%s %s' "$bytes" "${units[$i]}"
}

usage() {
  sed -n '3,27p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

# ---------------------------------------------------------------- arguments

while [ $# -gt 0 ]; do
  case "$1" in
    --output)       [ $# -ge 2 ] || die "--output needs a directory"; OUTPUT_DIR="$2"; shift 2 ;;
    --output=*)     OUTPUT_DIR="${1#--output=}"; shift ;;
    --allow-dirty)  ALLOW_DIRTY=1; shift ;;
    --skip-checks)  SKIP_CHECKS=1; shift ;;
    --no-packages)  BUILD_PACKAGES=0; shift ;;
    -h|--help)      usage 0 ;;
    -*)             die "unknown option: $1 (try --help)" ;;
    *)              [ -z "$TAG" ] || die "more than one tag given"; TAG="$1"; shift ;;
  esac
done

# --------------------------------------------------- 1. tag and version check

command -v git >/dev/null 2>&1 || die "git is required"
command -v cargo >/dev/null 2>&1 || die "cargo is required"

if [ "$ALLOW_DIRTY" -eq 0 ]; then
  git diff-index --quiet HEAD -- 2>/dev/null \
    || die "the working tree has uncommitted changes; commit or stash them first"
  [ -z "$(git ls-files --others --exclude-standard)" ] \
    || die "the working tree has untracked files; clean them or use --allow-dirty"
else
  warn "working-tree cleanliness check disabled (--allow-dirty)"
fi

if [ -z "$TAG" ]; then
  TAG="$(git tag --points-at HEAD | head -n 1 || true)"
  [ -n "$TAG" ] || die "HEAD carries no Git tag; pass the tag explicitly (scripts/release.sh v1.0.0)"
fi

git rev-parse -q --verify "refs/tags/$TAG" >/dev/null \
  || die "tag $TAG does not exist"

if [ "$ALLOW_DIRTY" -eq 0 ]; then
  tag_commit="$(git rev-list -n 1 "$TAG")"
  head_commit="$(git rev-parse HEAD)"
  [ "$tag_commit" = "$head_commit" ] \
    || die "tag $TAG points at $tag_commit but HEAD is $head_commit; check out the tag first"
fi

# Version from Cargo.toml, without needing extra tooling.
CARGO_VERSION="$(
  awk '
    /^\[package\]/ { in_pkg = 1; next }
    /^\[/          { in_pkg = 0 }
    in_pkg && /^version[[:space:]]*=/ {
      if (match($0, /"[^"]*"/)) { print substr($0, RSTART + 1, RLENGTH - 2); exit }
    }' Cargo.toml
)"
[ -n "$CARGO_VERSION" ] || die "cannot read the version from Cargo.toml"

TAG_VERSION="${TAG#v}"
[ "$TAG_VERSION" = "$CARGO_VERSION" ] \
  || die "version mismatch: Cargo.toml says $CARGO_VERSION, tag $TAG says $TAG_VERSION"

VERSION="$CARGO_VERSION"
log "releasing diple $VERSION from tag $TAG"

# ------------------------------------------------------------ 2. check suite

if [ "$SKIP_CHECKS" -eq 0 ]; then
  log "running the check suite"
  export INSTA_UPDATE=no
  info "cargo fmt --all --check"
  cargo fmt --all --check
  info "cargo clippy --all-targets --all-features -- -D warnings"
  cargo clippy --all-targets --all-features --locked -- -D warnings
  info "cargo test --all-features --locked"
  cargo test --all-features --locked
  info "cargo test --release --all-features --locked"
  cargo test --release --all-features --locked
else
  warn "check suite skipped (--skip-checks)"
fi

# ------------------------------------------------------------ 3. build targets

rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"
STAGE="$OUTPUT_DIR/.stage"
mkdir -p "$STAGE"

# Name of the CARGO_TARGET_<TRIPLE>_LINKER variable for a target.
linker_var_for() {
  printf 'CARGO_TARGET_%s_LINKER' "$(printf '%s' "$1" | tr 'a-z-' 'A-Z_')"
}

# Can we build this target here? Writes a human-readable reason to stdout and
# returns non-zero when not. Progress messages go to stderr so that callers can
# capture the reason with a command substitution.
target_is_available() {
  local target="$1" linker_var

  if command -v rustup >/dev/null 2>&1; then
    if ! rustup target list --installed 2>/dev/null | grep -qx "$target"; then
      info "installing rust std for $target" >&2
      if ! rustup target add "$target" >/dev/null 2>&1; then
        echo "rustup cannot install the std library for $target"
        return 1
      fi
    fi
  elif [ "$target" != "$HOST_TARGET" ]; then
    echo "rustup is not available, so only the host target can be built"
    return 1
  fi

  linker_var="$(linker_var_for "$target")"

  case "$target" in
    *-apple-darwin)
      # Building a macOS binary needs an Apple toolchain unless we are on macOS.
      if [ "${HOST_TARGET%-apple-darwin}" = "$HOST_TARGET" ] \
         && [ -z "${!linker_var:-}" ] \
         && ! command -v "${target}-clang" >/dev/null 2>&1 \
         && ! command -v zig >/dev/null 2>&1; then
        echo "no macOS cross toolchain (needs osxcross, zig, or a macOS host)"
        return 1
      fi
      ;;
    *-unknown-linux-musl)
      # rustc ships a self-contained musl libc, but the aarch64 cross build
      # still needs a cross linker when the host is not aarch64.
      if [ "$target" != "$HOST_TARGET" ] \
         && [ "${target%%-*}" != "${HOST_TARGET%%-*}" ] \
         && [ -z "${!linker_var:-}" ] \
         && ! command -v "${target%%-*}-linux-musl-gcc" >/dev/null 2>&1 \
         && ! command -v "${target%%-*}-linux-gnu-gcc" >/dev/null 2>&1; then
        echo "no ${target%%-*} cross linker (install gcc-${target%%-*}-linux-gnu or musl-cross)"
        return 1
      fi
      ;;
  esac
  return 0
}

build_target() {
  local target="$1" reason
  if ! reason="$(target_is_available "$target")"; then
    warn "$target: ${reason:-toolchain unavailable}"
    SKIPPED_TARGETS+=("$target (${reason:-toolchain unavailable})")
    return 0
  fi

  log "building $target"
  # Point cargo at a cross linker when one is present and nothing is configured.
  local linker_var linker
  linker_var="$(linker_var_for "$target")"
  if [ -z "${!linker_var:-}" ] && [ "$target" != "$HOST_TARGET" ]; then
    for linker in "${target%%-*}-linux-musl-gcc" "${target%%-*}-linux-gnu-gcc"; do
      if command -v "$linker" >/dev/null 2>&1; then
        export "$linker_var=$linker"
        info "using $linker for $target"
        break
      fi
    done
  fi

  # The default feature set uses oniguruma, which compiles C. musl targets
  # need a real musl compiler; the host's glibc cc emits _FORTIFY_SOURCE
  # symbols (__memcpy_chk) that musl does not provide.
  case "$target" in
    *-linux-musl)
      if command -v musl-gcc >/dev/null 2>&1; then
        export CC_x86_64_unknown_linux_musl=musl-gcc
        export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=musl-gcc
      else
        warn "$target: musl-gcc not found (install musl-tools); skipping"
        SKIPPED_TARGETS+=("$target (no musl C compiler)")
        return 0
      fi
      ;;
  esac

  if ! cargo build --release --locked --target "$target" 2>&1 | tail -n 20; then
    warn "$target: cargo build failed (missing linker or C toolchain?)"
    SKIPPED_TARGETS+=("$target (build failed)")
    return 0
  fi

  local binary="target/$target/release/diple"
  if [ ! -f "$binary" ]; then
    warn "$target: no binary produced at $binary"
    SKIPPED_TARGETS+=("$target (no binary)")
    return 0
  fi

  BUILT_TARGETS+=("$target")
  return 0
}

for t in "${ALL_TARGETS[@]}"; do
  build_target "$t"
done

[ "${#BUILT_TARGETS[@]}" -gt 0 ] || die "no target could be built"

# ---------------------------------- 4. man page and completions from the binary

# Prefer the natively runnable binary; a cross-built one cannot be executed.
GENERATOR=""
for t in "${BUILT_TARGETS[@]}"; do
  if [ "$t" = "$HOST_TARGET" ]; then
    GENERATOR="target/$t/release/diple"
    break
  fi
done
if [ -z "$GENERATOR" ]; then
  for t in "${BUILT_TARGETS[@]}"; do
    if "target/$t/release/diple" --version >/dev/null 2>&1; then
      GENERATOR="target/$t/release/diple"
      break
    fi
  done
fi
[ -n "$GENERATOR" ] || die "no natively runnable binary to generate the man page and completions"

log "generating the man page and shell completions with $GENERATOR"
"$GENERATOR" --generate-man > "$STAGE/diple.1"
[ -s "$STAGE/diple.1" ] || die "the generated man page is empty"
# Fail loudly if the page does not even name the program: that would mean the
# generator broke, and packages must never ship a broken man page.
grep -q '^\.TH diple' "$STAGE/diple.1" || die "the generated man page has no .TH header"

"$GENERATOR" --generate-completions bash > "$STAGE/diple.bash"
"$GENERATOR" --generate-completions zsh  > "$STAGE/_diple"
"$GENERATOR" --generate-completions fish > "$STAGE/diple.fish"
for f in "$STAGE/diple.bash" "$STAGE/_diple" "$STAGE/diple.fish"; do
  [ -s "$f" ] || die "generated completion $f is empty"
done

# Packaging metadata (Cargo.toml [package.metadata.deb] / [.generate-rpm])
# installs these from a fixed location; keep them where the metadata expects.
mkdir -p target/assets
cp "$STAGE/diple.1" "$STAGE/diple.bash" "$STAGE/_diple" "$STAGE/diple.fish" target/assets/

# ------------------------------------------------------------- 5. packages

deb_metadata_present() { grep -q 'package\.metadata\.deb' Cargo.toml; }
rpm_metadata_present() { grep -q 'package\.metadata\.generate-rpm' Cargo.toml; }

build_deb() {
  if ! command -v cargo-deb >/dev/null 2>&1; then
    warn ".deb: cargo-deb is not installed (cargo install cargo-deb)"
    SKIPPED_TARGETS+=(".deb (cargo-deb not installed)")
    return 0
  fi
  if ! deb_metadata_present; then
    warn ".deb: Cargo.toml has no [package.metadata.deb] section"
    SKIPPED_TARGETS+=(".deb (no [package.metadata.deb] in Cargo.toml)")
    return 0
  fi
  log "building the .deb package"
  if cargo deb --no-build --target "$HOST_TARGET" --output "$OUTPUT_DIR/"; then
    return 0
  fi
  warn ".deb: cargo deb failed"
  SKIPPED_TARGETS+=(".deb (cargo deb failed)")
}

build_rpm() {
  if ! command -v cargo-generate-rpm >/dev/null 2>&1; then
    warn ".rpm: cargo-generate-rpm is not installed (cargo install cargo-generate-rpm)"
    SKIPPED_TARGETS+=(".rpm (cargo-generate-rpm not installed)")
    return 0
  fi
  if ! rpm_metadata_present; then
    warn ".rpm: Cargo.toml has no [package.metadata.generate-rpm] section"
    SKIPPED_TARGETS+=(".rpm (no [package.metadata.generate-rpm] in Cargo.toml)")
    return 0
  fi
  log "building the .rpm package"
  if cargo generate-rpm --target "$HOST_TARGET" --output "$OUTPUT_DIR/"; then
    return 0
  fi
  warn ".rpm: cargo generate-rpm failed"
  SKIPPED_TARGETS+=(".rpm (cargo generate-rpm failed)")
}

if [ "$BUILD_PACKAGES" -eq 1 ]; then
  build_deb
  build_rpm
else
  warn "package building disabled (--no-packages)"
fi

# -------------------------------------------------------------- 6. tarballs

log "assembling tarballs"
for target in "${BUILT_TARGETS[@]}"; do
  name="diple-$VERSION-$target"
  root="$STAGE/$name"
  rm -rf "$root"
  mkdir -p "$root/completions"

  cp "target/$target/release/diple" "$root/diple"
  chmod 0755 "$root/diple"
  cp "$STAGE/diple.1" "$root/diple.1"
  cp "$STAGE/diple.bash" "$root/completions/diple.bash"
  cp "$STAGE/_diple"     "$root/completions/_diple"
  cp "$STAGE/diple.fish" "$root/completions/diple.fish"
  cp README.md LICENSE CHANGELOG.md "$root/"

  # Deterministic tarball: fixed owner, sorted entries, mtime from the tag.
  tar_mtime="$(git log -1 --format=%cI "$TAG")"
  tar --sort=name \
      --owner=0 --group=0 --numeric-owner \
      --mtime="$tar_mtime" \
      --format=gnu \
      -C "$STAGE" -cf "$STAGE/$name.tar" "$name"
  gzip -9n -c "$STAGE/$name.tar" > "$OUTPUT_DIR/$name.tar.gz"
  rm -f "$STAGE/$name.tar"

  # The bare binary is convenient for `curl | install`.
  cp "target/$target/release/diple" "$OUTPUT_DIR/diple-$VERSION-$target"
done

# Ship the generated man page and completions as loose artifacts too, so
# distro packagers do not have to unpack a tarball for them.
cp "$STAGE/diple.1" "$STAGE/diple.bash" "$STAGE/_diple" "$STAGE/diple.fish" "$OUTPUT_DIR/"

# --------------------------------------------------------- 7. release notes

log "extracting release notes for $VERSION from CHANGELOG.md"
NOTES="$OUTPUT_DIR/RELEASE_NOTES.md"
if [ -f CHANGELOG.md ]; then
  awk -v version="$VERSION" '
    # Match "## [1.0.0] - date" or "## 1.0.0".
    /^## / {
      if (found) exit
      line = $0
      gsub(/[][]/, "", line)
      if (line ~ ("^## " version "([^0-9.]|$)")) { found = 1; next }
      next
    }
    found { print }
  ' CHANGELOG.md > "$NOTES"
  # Drop leading/trailing blank lines.
  awk 'NF {p = 1} p' "$NOTES" | tac | awk 'NF {p = 1} p' | tac > "$NOTES.tmp"
  mv "$NOTES.tmp" "$NOTES"
fi
if [ ! -s "$NOTES" ]; then
  warn "CHANGELOG.md has no section for $VERSION; writing a placeholder"
  printf 'diple %s\n\nNo CHANGELOG.md section for this version.\n' "$VERSION" > "$NOTES"
fi
{
  printf '# diple %s\n\n' "$VERSION"
  cat "$NOTES"
} > "$NOTES.tmp"
mv "$NOTES.tmp" "$NOTES"

# ------------------------------------------------------------ 8. checksums

log "generating SHA256SUMS"
(
  cd "$OUTPUT_DIR"
  list="$(mktemp)"
  find . -maxdepth 1 -type f ! -name 'SHA256SUMS*' -printf '%P\n' \
    | LC_ALL=C sort > "$list"
  xargs -r -a "$list" sha256sum > SHA256SUMS
  rm -f "$list"
)

rm -rf "$STAGE"

# -------------------------------------------------------------- 9. summary

while IFS= read -r line; do
  ARTIFACTS+=("$line")
done < <(find "$OUTPUT_DIR" -maxdepth 1 -type f -printf '%P\n' | LC_ALL=C sort)

echo
log "release $TAG (version $VERSION) built into $OUTPUT_DIR/"
echo
printf '  %-52s %10s\n' "ARTIFACT" "SIZE"
printf '  %-52s %10s\n' "----------------------------------------------------" "----------"
for a in "${ARTIFACTS[@]}"; do
  printf '  %-52s %10s\n' "$a" "$(human_size "$OUTPUT_DIR/$a")"
done
echo
printf '  targets built:   %s\n' "${BUILT_TARGETS[*]}"
if [ "${#SKIPPED_TARGETS[@]}" -gt 0 ]; then
  echo "  skipped:"
  for s in "${SKIPPED_TARGETS[@]}"; do
    printf '    - %s\n' "$s"
  done
else
  echo "  skipped:         none"
fi
echo
echo "  Verify with:     (cd $OUTPUT_DIR && sha256sum -c SHA256SUMS)"
echo "  Release notes:   $NOTES"
echo
